import React from 'react';
import { Shield, Lock, FileText, ArrowLeft } from 'lucide-react';
import Button from '../components/common/Button';
import Badge from '../components/common/Badge';

export default function PrivacyPolicyView({ onNavigateHome }) {
  return (
    <div className="max-w-4xl mx-auto space-y-6 py-4 animate-fadeIn font-sans text-xs">
      {/* Header */}
      <div className="flex justify-between items-center pb-4 border-b border-slate-200">
        <div className="space-y-1">
          <div className="flex items-center gap-2">
            <Shield className="w-5 h-5 text-purple-700" />
            <h2 className="font-sans font-bold text-xl text-slate-900">
              Institutional Privacy Policy & Data Governance
            </h2>
          </div>
          <span className="font-mono text-[10px] text-slate-500">
            Effective Date: September 2026 · Version: 2.4-GOV
          </span>
        </div>
        <Button variant="ghost" size="sm" icon={ArrowLeft} onClick={onNavigateHome}>
          Back to Cockpit
        </Button>
      </div>

      <div className="cockpit-card p-6 space-y-5 bg-white border border-slate-200 text-slate-700 leading-relaxed shadow-sm">
        <div className="space-y-2">
          <h3 className="text-sm font-semibold text-slate-900">1. Data Ownership & Scope</h3>
          <p>
            PAIMANA AI operates under the auspices of the{' '}
            <strong className="text-purple-800">[OFFICIAL ORGANIZATION: Infrastructure & Project Monitoring Division (IPMD), Ministry of Statistics and Programme Implementation (MoSPI), Government of India]</strong>.
            This privacy specification defines the handling of central sector project telemetry, financial disbursement audits, and model reasoning artifacts.
          </p>
        </div>

        <div className="space-y-2">
          <h3 className="text-sm font-semibold text-slate-900">2. Collection of Infrastructure Telemetry</h3>
          <p>
            The platform processes public sector project milestones, expenditure reports, and GCC contract documents. No personally identifiable citizen records are collected or retained by the machine learning prediction models.
          </p>
        </div>

        <div className="space-y-2">
          <h3 className="text-sm font-semibold text-slate-900">3. Artificial Intelligence & RAG Grounding</h3>
          <p>
            Model predictions generated by XGBoost and pgvector RAG are governed by Section 23 immutable audit logging. All generative multi-agent recommendations serve strictly as advisory decision-support and do not execute binding administrative actions without human authorization.
          </p>
        </div>

        <div className="space-y-2">
          <h3 className="text-sm font-semibold text-slate-900">4. Session Telemetry & Preferences</h3>
          <p>
            Local browser storage (`localStorage`) is utilized exclusively to maintain interface state, filter selections, and cookie consent preferences. No commercial third-party advertising trackers are embedded.
          </p>
        </div>

        <div className="space-y-2 pt-2 border-t border-slate-100">
          <h3 className="text-sm font-semibold text-slate-900">5. Official Contact Point</h3>
          <p>
            For institutional data queries, contract audits, or security inquiries, please contact:{' '}
            <span className="font-mono text-purple-700 font-semibold">[OFFICIAL CONTACT EMAIL: ipmd-support@mospi.gov.in]</span>{' '}
            at{' '}
            <span className="font-mono text-slate-600">[OFFICIAL ORGANIZATION ADDRESS: Sardar Patel Bhawan, Sansad Marg, New Delhi, 110001, India]</span>.
          </p>
        </div>
      </div>
    </div>
  );
}
